### ISSUE TITLE
Hardcoded path at line 38 in tiles_classification/define_clusters_KNN.py

### ISSUE THREAD

**Issue by aelhammad** [GlastonburyC/RNAPath#1]
Hi, I was trying to run the tile_classification pipeline but I found this hardcoded path: 

`    images = glob.glob(f'/group/glastonbury/gtex-proto-class-labels/{args.folder_name}/**/' + c + '_128/*.jpg')`

Is there folder in this repository  containing this information? If not It would be possible to provide or clarify how to generate this data

Your paper is very nice by the way :)

**Comment by GlastonburyC** [comment]
Hi @aelhammad - Thanks for your kind words - We are glad you enjoyed the paper. 

We should definitely factor out the hardcoded path. In the meantime, the annotations are linked in the README at the bottom. You can download them from [here](https://drive.google.com/file/d/1syzB4Upr39jDgEhRiegVFQUexxD8w3jN/view).

Let me know if that works for you.
