### ISSUE TITLE
Dino model training

### ISSUE THREAD

**Issue by aelhammad** [GlastonburyC/RNAPath#2]
Is there detailed information on how the model was trained? According to the paper, the model was trained using approximately 14,000 whole slide images (WSIs) from which 1.7 million tiles were extracted. 

This averages out to about 120 tiles per slide. However, the patching method you provided appears to result in a significantly higher number of tiles per slide. Did you use another tile size for training ?

**Comment by francescocister** [comment]
Hi @aelhammad,
Indeed the model was trained on 1.7 million patches and the tile size is the same as in the preprocessing (128). We simply sampled a low number of patches per WSI, instead of using all of them.

**Comment by aelhammad** [comment]
Good to know, thank you @francescocister !

**Comment by francescocister** [comment]
Welcome! :)
